name: Minders
description: Minders student activity application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.7
  http: ^0.12.0+4
  url_launcher: ^5.5.0
  flutter_svg: ^0.18.0
  cupertino_icons: ^0.1.2
  get:
  animated_splash: ^1.0.0
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"
  build_runner: ^1.10.1
  json_serializable: ^3.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_black_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: englishBebas
      fonts:
        - asset: assets/fonts/BebasNeue_Bold.ttf
        - asset: assets/fonts/BebasNeue_Regular.ttf
        - asset: assets/fonts/BebasNeue_Book.ttf
    - family: englishTex
      fonts:
        - asset: assets/fonts/texgyre_bold.otf
        - asset: assets/fonts/texgyre_regular.otf
    - family: arabic
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Light.ttf
